'use strict';
/* ════════════════════════════════════════════════════════════
   AUDIOPIX — app.js  (Code-System Edition)

   PROTOCOL:
     1. START TONE  — 180 Hz for 300 ms  (sync / "begin" signal)
     2. PRE-GAP     — 60 ms silence
     3. PIXEL DATA  — n*n tones, each toneMs long, gapped by PX_GAP ms
     4. END TONE    — 5500 Hz for 400 ms
     5. RESUME TONE — 180 Hz for 200 ms (sent by TX after a pause/resume)

   Image size, color count, and tone speed are NOT encoded in tones.
   They are exchanged via a 9-character transfer code (XXXX-XXXX-X)
   generated by the transmitter and entered by the receiver.

   TX uses a SINGLE oscillator with a real-time lookahead scheduler.
   This allows true pause/resume without rebuilding the audio graph.
═════════════════════════════════════════════════════════════ */

// ──────────────────────────────────────────
//  PROTOCOL PARAMETERS
// ──────────────────────────────────────────
const P = {
  FREQ_LO:   600,    // Hz — data band low
  FREQ_HI:  4500,    // Hz — data band high

  SYNC_F:    180,    // Hz — start / resume carrier
  SYNC_MS:   300,    // ms — start tone duration
  RESUME_MS: 200,    // ms — resume-after-pause tone duration

  END_F:    5500,    // Hz — end marker
  END_MS:    400,    // ms

  PX_GAP:      4,    // ms — silence between pixel tones
  PRE_GAP:    60,    // ms — silence before data starts (after start tone)
  ATT:       0.005,  // s  — tone attack
  REL:       0.005,  // s  — tone release

  // Detection thresholds
  SYNC_TH:    55,    // magnitude for sync detect
  DATA_TH:    28,    // magnitude for data tones
  END_TH:     45,    // magnitude for end tone

  // Lookahead scheduler
  LOOKAHEAD:  0.15,  // s — schedule this far ahead
  SCHED_INT:  25,    // ms — scheduler tick
};

// ──────────────────────────────────────────
//  CONFIG  (applied settings)
// ──────────────────────────────────────────
const CFG = { resolution: 32, nColors: 124, timeMs: 50 };
const PND = { ...CFG };  // pending (popup, unapplied)

// ──────────────────────────────────────────
//  STATE
// ──────────────────────────────────────────
let mode      = 'tx';
let palette   = [];
let txPixels  = null;
let origImg   = null;
let isTx      = false;
let txAC      = null;

// TX real-time scheduler state
let txOsc          = null;
let txGainNode     = null;
let txMasterNode   = null;
let txCurrentPixel = 0;     // next pixel index to schedule
let txSchedTime    = 0;     // next scheduled audio time
let txDataStartAC  = 0;     // AudioContext time when data phase began
let txPaused       = false;
let txSchedTimer   = null;
let curTxFreq      = 0;     // for spectrum display

// RX state
let isRx      = false;
let rxAC      = null;
let rxStream  = null;
let rxAna     = null;
let rxFD      = null;
let rxFR      = 1;
let rxTimer   = null;
let rxRAF     = null;

let rxPhase      = 'IDLE';   // IDLE | SYNC | DATA | DONE
let rxSyncDet    = 0;
let rxSyncGone   = 0;
let rxDetCFG     = null;     // { resolution, nColors, timeMs } from entered code
let rxDataStart  = 0;        // performance.now() anchor for pixel timing
let rxLastPx     = -1;
let rxPixels     = [];
let rxPxCnt      = 0;
let rxUserPaused = false;
let rxPauseAnchor = 0;       // time when RX user hit pause
let rxTxPaused   = false;    // detected TX has gone silent
let rxLastSig    = 0;        // last time a data-band signal was heard

// Resume-sync detection inside DATA phase
let rxResumeSyncStart = 0;   // time 180Hz first detected in DATA
let rxResumeSyncGone  = 0;

// Code state
let rxCode = null;           // { resolution, nColors, timeMs } from entered code

// ──────────────────────────────────────────
//  HELPERS
// ──────────────────────────────────────────
const $ = id => document.getElementById(id);
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

function idx2freq(i, n)  { return P.FREQ_LO + (i / (n - 1)) * (P.FREQ_HI - P.FREQ_LO); }
function freq2idx(f, n)  { return clamp(Math.round((f - P.FREQ_LO) / (P.FREQ_HI - P.FREQ_LO) * (n - 1)), 0, n - 1); }

function fmtTime(ms) {
  if (ms < 1000)   return `${ms.toFixed(0)} ms`;
  if (ms < 60000)  return `${(ms / 1000).toFixed(1)} s`;
  const m = Math.floor(ms / 60000), s = Math.floor((ms % 60000) / 1000);
  if (ms < 3600000) return s ? `${m}m ${s}s` : `${m}m`;
  const h = Math.floor(ms / 3600000), rm = Math.floor((ms % 3600000) / 60000);
  return rm ? `${h}h ${rm}m` : `${h}h`;
}

// ──────────────────────────────────────────
//  CODE ENCODE / DECODE
//  Format: XXXX-XXXX-X  (9 base-36 alphanum + 2 dashes)
//  Group 1 (4): resolution 1–6000   → (res-1) base-36 padded
//  Group 2 (4): nColors + timeMs    → ncIdx*200 + (tm-1)
//  Group 3 (1): checksum            → sum of g1+g2 char values mod 36
// ──────────────────────────────────────────
function encodeCode(res, nc, tm) {
  const g1 = (res - 1).toString(36).toUpperCase().padStart(4, '0');
  const ncIdx = Math.round((clamp(nc, 32, 300) - 32) / 4);
  const tmIdx = clamp(tm - 1, 0, 199);
  const g2 = (ncIdx * 200 + tmIdx).toString(36).toUpperCase().padStart(4, '0');
  let cs = 0;
  for (const c of g1 + g2) cs += parseInt(c, 36);
  const g3 = (cs % 36).toString(36).toUpperCase();
  return `${g1}-${g2}-${g3}`;
}

function decodeCode(raw) {
  const clean = raw.replace(/[-\s]/g, '').toUpperCase();
  if (clean.length !== 9) return null;
  if (!/^[0-9A-Z]{9}$/.test(clean)) return null;

  const g1 = clean.slice(0, 4);
  const g2 = clean.slice(4, 8);
  const g3 = clean.slice(8, 9);

  let cs = 0;
  for (const c of g1 + g2) cs += parseInt(c, 36);
  if ((cs % 36).toString(36).toUpperCase() !== g3) return null;

  const res  = parseInt(g1, 36) + 1;
  const g2v  = parseInt(g2, 36);
  const nc   = Math.floor(g2v / 200) * 4 + 32;
  const tm   = (g2v % 200) + 1;

  if (res < 1 || res > 6000 || nc < 32 || nc > 300 || tm < 1 || tm > 200) return null;
  return { resolution: res, nColors: nc, timeMs: tm };
}

function updateTxCode() {
  const code = encodeCode(CFG.resolution, CFG.nColors, CFG.timeMs);
  $('txCodeDisplay').textContent = code;
  if ($('settingsCodeVal')) $('settingsCodeVal').textContent = code;
}

async function copyCode() {
  const code = $('txCodeDisplay').textContent;
  if (!code || code === '—') return;
  try {
    await navigator.clipboard.writeText(code);
  } catch (_) {
    // fallback
    const el = document.createElement('textarea');
    el.value = code; document.body.appendChild(el);
    el.select(); document.execCommand('copy');
    document.body.removeChild(el);
  }
  const btn = $('btnCopyCode');
  btn.textContent = '✓ COPIED';
  btn.classList.add('copied');
  setTimeout(() => { btn.innerHTML = `<svg viewBox="0 0 14 14" fill="none" width="11" height="11"><rect x="1" y="4" width="9" height="9" rx="1.5" stroke="currentColor" stroke-width="1.3"/><path d="M4 4V2.5A1.5 1.5 0 0 1 5.5 1H11.5A1.5 1.5 0 0 1 13 2.5V8.5A1.5 1.5 0 0 1 11.5 10H10" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/></svg> COPY`; btn.classList.remove('copied'); }, 1600);
}

// ──────────────────────────────────────────
//  CODE ENTRY POPUP
// ──────────────────────────────────────────
function showCodeEntry() {
  $('codeInput').value = '';
  $('codeInputStatus').textContent = '';
  $('codeInputStatus').className   = 'code-input-status';
  $('codeInput').className         = 'code-input';
  $('codeDecodedPreview').className = 'code-decoded-preview';
  $('codeDecodedPreview').textContent = '';
  $('codeOverlay').classList.remove('hidden');
  setTimeout(() => $('codeInput').focus(), 200);
}

function closeCodeEntry() {
  $('codeOverlay').classList.add('hidden');
}

function codeOverlayClick(e) {
  if (e.target === $('codeOverlay')) closeCodeEntry();
}

function formatCodeInput(el) {
  let v = el.value.replace(/[^0-9A-Za-z]/g, '').toUpperCase().slice(0, 9);
  let out = '';
  for (let i = 0; i < v.length; i++) {
    if (i === 4 || i === 8) out += '-';
    out += v[i];
  }
  el.value = out;

  // Live validation
  const decoded = decodeCode(v);
  if (v.length === 9) {
    if (decoded) {
      el.className = 'code-input valid';
      $('codeInputStatus').textContent = '✓ Valid code';
      $('codeInputStatus').className   = 'code-input-status ok';
      $('codeDecodedPreview').innerHTML =
        `${decoded.resolution}×${decoded.resolution} pixels &nbsp;·&nbsp; ` +
        `${decoded.nColors} colors &nbsp;·&nbsp; ${decoded.timeMs}ms/tone`;
      $('codeDecodedPreview').className = 'code-decoded-preview visible';
    } else {
      el.className = 'code-input invalid';
      $('codeInputStatus').textContent = '✗ Invalid code — check and try again';
      $('codeInputStatus').className   = 'code-input-status err';
      $('codeDecodedPreview').className = 'code-decoded-preview';
    }
  } else {
    el.className = 'code-input';
    $('codeInputStatus').textContent = '';
    $('codeInputStatus').className   = 'code-input-status';
    $('codeDecodedPreview').className = 'code-decoded-preview';
  }
}

function submitCode() {
  const raw     = $('codeInput').value;
  const decoded = decodeCode(raw);
  if (!decoded) {
    $('codeInputStatus').textContent = '✗ Invalid code — check and try again';
    $('codeInputStatus').className   = 'code-input-status err';
    $('codeInput').classList.add('invalid');
    return;
  }

  rxCode = decoded;
  buildPalette(decoded.nColors);

  $('rxCodeVal').textContent = raw.replace(/[^0-9A-Za-z\-]/g, '').toUpperCase();
  $('rxStatus').textContent  = `Code accepted — ${decoded.resolution}×${decoded.resolution} · ${decoded.nColors}c · ${decoded.timeMs}ms`;
  setRxPhase('READY', `${decoded.resolution}×${decoded.resolution} · ${decoded.nColors} colors · ${decoded.timeMs}ms/tone`);

  closeCodeEntry();
}

// ──────────────────────────────────────────
//  ESTIMATION
// ──────────────────────────────────────────
function calcEst(res, nc, ms) {
  const pixels  = res * res;
  const startMs = P.SYNC_MS;
  const dataMs  = pixels * (ms + P.PX_GAP);
  const endMs   = P.PRE_GAP + P.END_MS;
  const total   = startMs + P.PRE_GAP + dataMs + endMs;
  return { pixels, startMs, dataMs, endMs, total };
}

// ──────────────────────────────────────────
//  PALETTE
// ──────────────────────────────────────────
function hsl2rgb(h, s, l) {
  s /= 100; l /= 100;
  const k = n => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = n => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [~~(f(0) * 255), ~~(f(8) * 255), ~~(f(4) * 255)];
}

function buildPalette(n) {
  palette = [];
  const chromatic = Math.max(0, n - 4);
  const tiers = [[92,20],[85,35],[78,50],[70,65],[62,79]];
  for (let i = 0; i < chromatic; i++) {
    const [s, l] = tiers[i % tiers.length];
    palette.push(hsl2rgb((i * 137.508) % 360, s, l));
  }
  palette.push([10,10,12], [80,80,88], [165,165,175], [242,242,248]);
}

function quantize(r, g, b) {
  let best = 0, d = Infinity;
  for (let i = 0; i < palette.length; i++) {
    const [pr, pg, pb] = palette[i];
    const dd = 0.2126*(r-pr)**2 + 0.7152*(g-pg)**2 + 0.0722*(b-pb)**2;
    if (dd < d) { d = dd; best = i; }
  }
  return best;
}

// ──────────────────────────────────────────
//  ANIMATED BACKGROUND
// ──────────────────────────────────────────
const bgCV = $('bgCanvas');
const bgCX = bgCV.getContext('2d');
let bgT = 0;

function resizeBg() { bgCV.width = innerWidth; bgCV.height = innerHeight; }
resizeBg();
addEventListener('resize', resizeBg);

(function animBg() {
  const W = bgCV.width, H = bgCV.height;
  bgCX.clearRect(0, 0, W, H);
  const colFn = mode === 'tx'
    ? a => `rgba(255,117,53,${a})`
    : a => `rgba(0,212,200,${a})`;
  for (let w = 0; w < 8; w++) {
    const ph  = bgT * 0.00038 + w * 0.85;
    const amp = 18 + w * 15;
    const fq  = 0.0028 + w * 0.0017;
    const yb  = H * (0.08 + w * 0.12);
    const env = Math.sin(bgT * 0.00022 + w * 0.44);
    bgCX.beginPath();
    bgCX.moveTo(0, yb);
    for (let x = 0; x <= W; x += 3) bgCX.lineTo(x, yb + Math.sin(x * fq + ph) * amp * env);
    bgCX.strokeStyle = colFn(0.018 + w * 0.01);
    bgCX.lineWidth = 1;
    bgCX.stroke();
  }
  bgT++;
  requestAnimationFrame(animBg);
})();

// ──────────────────────────────────────────
//  MODE
// ──────────────────────────────────────────
function setMode(m) {
  mode = m;
  const tx = m === 'tx';
  $('btnTx').className    = 'mode-btn' + (tx  ? ' active-tx' : '');
  $('btnRx').className    = 'mode-btn' + (!tx ? ' active-rx' : '');
  $('txPanel').className  = 'panel tx-panel' + (tx  ? '' : ' hidden');
  $('rxPanel').className  = 'panel rx-panel' + (!tx ? '' : ' hidden');

  // Show code entry popup automatically if RX and no code yet
  if (!tx && !rxCode) {
    setTimeout(showCodeEntry, 200);
  }
}

// ──────────────────────────────────────────
//  DEVICE ENUMERATION
// ──────────────────────────────────────────
async function enumDevices() {
  try { const t = await navigator.mediaDevices.getUserMedia({audio:true}); t.getTracks().forEach(t=>t.stop()); } catch(_) {}
  const devs = await navigator.mediaDevices.enumerateDevices().catch(() => []);

  const spkSel = $('spkSel');
  spkSel.innerHTML = '<option value="">Default Speaker</option>';
  devs.filter(d => d.kind === 'audiooutput').forEach((d, i) => spkSel.add(new Option(d.label || `Speaker ${i+1}`, d.deviceId)));
  spkSel.addEventListener('change', () => badge('spkBadge', spkSel));
  badge('spkBadge', spkSel);

  const micSel = $('micSel');
  micSel.innerHTML = '';
  devs.filter(d => d.kind === 'audioinput').forEach((d, i) => micSel.add(new Option(d.label || `Mic ${i+1}`, d.deviceId)));
  micSel.addEventListener('change', () => badge('micBadge', micSel));
  badge('micBadge', micSel);
}

function badge(id, sel) {
  const l = sel.options[sel.selectedIndex]?.text || '—';
  $(id).textContent = l.length > 18 ? l.slice(0, 16) + '…' : l;
}

function onMicChange() { if (isRx) { stopRx(); startRx(); } }

// ──────────────────────────────────────────
//  IMAGE LOADING
// ──────────────────────────────────────────
const dropZone = $('dropZone');
const fileInEl = $('fileInput');
const prevCV   = $('previewCanvas');
const prevCX   = prevCV.getContext('2d');

dropZone.addEventListener('click', () => fileInEl.click());
dropZone.addEventListener('dragover', e => { e.preventDefault(); dropZone.classList.add('drag-over'); });
dropZone.addEventListener('dragleave', e => { if (!dropZone.contains(e.relatedTarget)) dropZone.classList.remove('drag-over'); });
dropZone.addEventListener('drop', e => {
  e.preventDefault(); dropZone.classList.remove('drag-over');
  const f = e.dataTransfer.files[0];
  if (f && f.type.startsWith('image/')) loadFile(f);
});
fileInEl.addEventListener('change', e => { if (e.target.files[0]) loadFile(e.target.files[0]); });

function loadFile(file) {
  const rd = new FileReader();
  rd.onload = ev => {
    const img = new Image();
    img.onload = () => { origImg = img; renderPreview(img); processImage(img, CFG.resolution, CFG.nColors); };
    img.src = ev.target.result;
  };
  rd.readAsDataURL(file);
}

function renderPreview(img) {
  prevCV.width  = dropZone.offsetWidth  || 500;
  prevCV.height = dropZone.offsetHeight || 188;
  const sc = Math.min(prevCV.width / img.width, prevCV.height / img.height);
  const dw = img.width * sc, dh = img.height * sc;
  prevCX.clearRect(0, 0, prevCV.width, prevCV.height);
  prevCX.drawImage(img, (prevCV.width - dw) / 2, (prevCV.height - dh) / 2, dw, dh);
  dropZone.classList.add('loaded');
}

function processImage(img, res, nc) {
  buildPalette(nc);
  const oc = Object.assign(document.createElement('canvas'), { width: res, height: res });
  const ox = oc.getContext('2d');
  ox.drawImage(img, 0, 0, res, res);
  const dat = ox.getImageData(0, 0, res, res).data;
  txPixels = new Uint8Array(res * res);
  for (let i = 0; i < res * res; i++) txPixels[i] = quantize(dat[i*4], dat[i*4+1], dat[i*4+2]);

  $('btnTransmit').disabled = false;
  $('btnPreview').disabled  = false;
  $('dropInfo').textContent = `${res}×${res} · ${(res*res).toLocaleString()} px · ${nc} colors`;
  setTxMsg(`Ready — ${(res*res).toLocaleString()} pixels`);
}

// ──────────────────────────────────────────
//  PREVIEW MODAL
// ──────────────────────────────────────────
function showPreview() {
  if (!txPixels || !origImg) return;
  const res = CFG.resolution;
  const DISP = 240;
  const sc   = Math.min(DISP / origImg.width, DISP / origImg.height);
  const ow   = Math.round(origImg.width * sc), oh = Math.round(origImg.height * sc);
  const origC = $('origThumb');
  origC.width = ow; origC.height = oh;
  origC.style.width = ow+'px'; origC.style.height = oh+'px';
  origC.getContext('2d').drawImage(origImg, 0, 0, ow, oh);

  const qtC = $('quantThumb');
  qtC.width = res; qtC.height = res;
  const disp = Math.min(DISP, Math.max(80, res * Math.floor(DISP / res)));
  qtC.style.width = disp+'px'; qtC.style.height = disp+'px';
  const qtX = qtC.getContext('2d');
  for (let i = 0; i < txPixels.length; i++) {
    const [r, g, b] = palette[txPixels[i]] || [0,0,0];
    qtX.fillStyle = `rgb(${r},${g},${b})`;
    qtX.fillRect(i % res, Math.floor(i / res), 1, 1);
  }

  const est = calcEst(res, CFG.nColors, CFG.timeMs);
  $('prevMeta').textContent = `${res}×${res} px  ·  ${CFG.nColors} colors  ·  ${CFG.timeMs}ms/tone  ·  ${fmtTime(est.total)} total`;
  $('prevOverlay').classList.remove('hidden');
}

function closePreview()      { $('prevOverlay').classList.add('hidden'); }
function closePrevOverlay(e) { if (e.target === $('prevOverlay')) closePreview(); }

// ──────────────────────────────────────────
//  TRANSMITTER — real-time lookahead scheduler
// ──────────────────────────────────────────
async function handleTransmitClick() {
  if (isTx) { stopTx(); return; }
  if (!txPixels) return;

  const btn = $('btnTransmit');
  btn.disabled = true;
  $('btnPreview').disabled = true;

  const pctEl = $('progPct');
  pctEl.textContent = 'LOADING';
  pctEl.classList.add('loading');
  setTxMsg('Processing…');
  $('progDetail').textContent = 'Preparing transmission…';

  if (origImg) processImage(origImg, CFG.resolution, CFG.nColors);
  await new Promise(r => setTimeout(r, 800));

  pctEl.classList.remove('loading');
  btn.disabled = false;
  $('btnPreview').disabled = false;
  startTx();
}

function startTx() {
  if (!txPixels) return;
  isTx       = true;
  txPaused   = false;
  txCurrentPixel = 0;

  const btn = $('btnTransmit');
  btn.textContent = 'STOP TX';
  btn.classList.add('stopping');
  $('btnPauseTx').disabled = false;
  $('btnPauseTx').textContent = '⏸ PAUSE';
  $('btnPauseTx').classList.remove('active');
  $('txLed').className = 'led on-tx';
  setTxMsg('Initialising audio…');

  try {
    txAC = new (window.AudioContext || window.webkitAudioContext)();

    const spkId = $('spkSel').value;
    if (spkId && txAC.setSinkId) txAC.setSinkId(spkId).catch(() => {});

    txMasterNode = txAC.createGain();
    txMasterNode.gain.value = 0.88;
    txMasterNode.connect(txAC.destination);

    txOsc = txAC.createOscillator();
    txGainNode = txAC.createGain();
    txOsc.type = 'sine';
    txOsc.connect(txGainNode);
    txGainNode.connect(txMasterNode);
    txGainNode.gain.setValueAtTime(0, 0);
    txOsc.start();

    // Schedule the start tone (180Hz, SYNC_MS)
    let t = txAC.currentTime + 0.06;
    scheduleNote(P.SYNC_F, t, P.SYNC_MS / 1000, 0.88);
    t += P.SYNC_MS / 1000 + P.PRE_GAP / 1000;

    txDataStartAC = t;
    txSchedTime   = t;

    // Start scheduler after start tone finishes
    const startDelay = (P.SYNC_MS + P.PRE_GAP + 80);
    txSchedTimer = setTimeout(() => runTxScheduler(), startDelay);

    startTxSpec();
    setTxMsg('Transmitting…');
    trackTxProgress();

  } catch(err) {
    setTxMsg(`Error: ${err.message}`);
    finishTx(false);
  }
}

function scheduleNote(freq, t0, durS, vol) {
  const attS = P.ATT, relS = P.REL;
  const dur  = Math.max(attS + relS + 0.002, durS);
  txOsc.frequency.setValueAtTime(freq, t0);
  txGainNode.gain.setValueAtTime(0, t0);
  txGainNode.gain.linearRampToValueAtTime(vol, t0 + attS);
  txGainNode.gain.setValueAtTime(vol, t0 + dur - relS);
  txGainNode.gain.linearRampToValueAtTime(0, t0 + dur);
}

function runTxScheduler() {
  if (!isTx || txPaused || !txAC) return;

  const toneS = CFG.timeMs / 1000;
  const gapS  = P.PX_GAP / 1000;
  const nc    = CFG.nColors;
  const now   = txAC.currentTime;
  const ahead = now + P.LOOKAHEAD;

  while (txSchedTime < ahead) {
    if (txCurrentPixel >= txPixels.length) {
      // Schedule end tone
      scheduleNote(P.END_F, txSchedTime, P.END_MS / 1000, 0.72);
      const delay = Math.max(50, (txSchedTime - now + P.END_MS / 1000 + 0.3) * 1000);
      setTimeout(() => finishTx(true), delay);
      txSchedTimer = null;
      return;
    }
    const freq = idx2freq(txPixels[txCurrentPixel], nc);
    scheduleNote(freq, txSchedTime, toneS, 0.86);
    txSchedTime += toneS + gapS;
    txCurrentPixel++;
  }

  txSchedTimer = setTimeout(runTxScheduler, P.SCHED_INT);
}

function togglePauseTx() {
  if (!isTx) return;
  if (txPaused) resumeTx(); else pauseTx();
}

function pauseTx() {
  if (!isTx || txPaused) return;
  txPaused = true;
  clearTimeout(txSchedTimer); txSchedTimer = null;

  // Cancel all future scheduled audio values
  const now = txAC.currentTime + 0.01;
  txGainNode.gain.cancelScheduledValues(now);
  txGainNode.gain.setValueAtTime(0, now);
  txOsc.frequency.cancelScheduledValues(now);

  // Back-calculate which pixel actually played at this moment
  const toneS  = CFG.timeMs / 1000;
  const gapS   = P.PX_GAP / 1000;
  const period = toneS + gapS;
  const elapsed = txAC.currentTime - txDataStartAC;
  const playedSoFar = Math.max(0, Math.min(Math.floor(elapsed / period), txPixels.length));
  txCurrentPixel = playedSoFar;
  // Schedule time will be reset when resuming

  $('btnPauseTx').textContent = '▶ RESUME';
  $('btnPauseTx').classList.add('active');
  $('txLed').className = 'led on-tx paused';
  setTxMsg('Paused — press Resume to continue');
}

function resumeTx() {
  if (!isTx || !txPaused) return;
  txPaused = false;

  const toneS = CFG.timeMs / 1000;
  const gapS  = P.PX_GAP / 1000;
  const period = toneS + gapS;

  // Play a resume-sync tone (180Hz), then continue data
  const t = txAC.currentTime + 0.05;
  scheduleNote(P.SYNC_F, t, P.RESUME_MS / 1000, 0.75);

  // Recalculate data anchor: pixel N will play at t + RESUME_MS + PRE_GAP
  // So txDataStartAC should be set such that pixel txCurrentPixel starts at t+RESUME_MS+PRE_GAP
  txDataStartAC = t + P.RESUME_MS / 1000 + P.PRE_GAP / 1000 - txCurrentPixel * period;
  txSchedTime   = t + P.RESUME_MS / 1000 + P.PRE_GAP / 1000;

  $('btnPauseTx').textContent = '⏸ PAUSE';
  $('btnPauseTx').classList.remove('active');
  $('txLed').className = 'led on-tx';
  setTxMsg('Resuming…');

  const delay = (P.RESUME_MS + P.PRE_GAP + 60);
  txSchedTimer = setTimeout(runTxScheduler, delay);
}

function stopTx() {
  isTx = false;
  txPaused = false;
  clearTimeout(txSchedTimer); txSchedTimer = null;
  if (txOsc) { try { txOsc.stop(); } catch(_) {} txOsc = null; }
  if (txAC)  { txAC.close().catch(() => {}); txAC = null; }
  txGainNode = null; txMasterNode = null;
  finishTx(false);
}

function finishTx(ok) {
  isTx = false; txPaused = false; curTxFreq = 0;
  clearTimeout(txSchedTimer); txSchedTimer = null;
  stopTxSpec();
  if (txAC && ok) { txAC.close().catch(() => {}); txAC = null; }

  const btn = $('btnTransmit');
  btn.textContent = 'TRANSMIT';
  btn.classList.remove('stopping');
  btn.disabled = !txPixels;
  $('btnPreview').disabled = !txPixels;
  $('btnPauseTx').disabled = true;
  $('btnPauseTx').textContent = '⏸ PAUSE';
  $('btnPauseTx').classList.remove('active');
  $('txLed').className = 'led';
  if (!ok) setProgress(0);
}

function trackTxProgress() {
  if (!isTx) return;
  if (!txPaused) {
    const total   = txPixels ? txPixels.length : 1;
    const current = clamp(txCurrentPixel, 0, total);
    const pct     = current / total;

    setProgress(pct);
    const remMs = Math.max(0, (total - current) * (CFG.timeMs + P.PX_GAP));
    $('progDetail').textContent = pct < 1
      ? `${current.toLocaleString()} / ${total.toLocaleString()} px — ${fmtTime(remMs)} left`
      : 'Complete ✓';
    setTxMsg('Transmitting…');

    // Update spectrum freq indicator
    if (current > 0 && current < total) {
      curTxFreq = idx2freq(txPixels[Math.min(current, total-1)], CFG.nColors);
    } else {
      curTxFreq = pct === 0 ? P.SYNC_F : 0;
    }
  }
  requestAnimationFrame(trackTxProgress);
}

function setProgress(p) {
  const pct = Math.round(p * 100);
  $('progFill').style.width = `${pct}%`;
  if (!$('progPct').classList.contains('loading'))
    $('progPct').textContent = p > 0 ? `${pct}%` : '—';
}

function setTxMsg(m) { $('txStatus').textContent = m; }

// ──────────────────────────────────────────
//  TX SPECTRUM
// ──────────────────────────────────────────
const N_BARS = 54;
let txSpecRAF = null;

function buildSpecBars() {
  const c = $('specBars');
  c.innerHTML = '';
  for (let i = 0; i < N_BARS; i++) {
    const b = document.createElement('div');
    b.className = 'spec-bar'; b.id = `sb${i}`;
    c.appendChild(b);
  }
}

function startTxSpec() {
  function frame() {
    for (let i = 0; i < N_BARS; i++) {
      const f    = P.FREQ_LO + (i / (N_BARS - 1)) * (P.FREQ_HI - P.FREQ_LO);
      const dist = Math.abs(f - curTxFreq);
      const span = (P.FREQ_HI - P.FREQ_LO) / 7;
      const iten = Math.max(0, 1 - dist / span);
      const h    = Math.max(2, iten * 40 + (isTx && !txPaused ? Math.random() * 3 : 0));
      const el   = document.getElementById(`sb${i}`);
      if (el) {
        el.style.height     = `${h}px`;
        el.style.background = `rgba(255,117,53,${0.18 + iten * 0.80})`;
      }
    }
    txSpecRAF = requestAnimationFrame(frame);
  }
  if (txSpecRAF) cancelAnimationFrame(txSpecRAF);
  frame();
}

function stopTxSpec() {
  if (txSpecRAF) { cancelAnimationFrame(txSpecRAF); txSpecRAF = null; }
  document.querySelectorAll('.spec-bar').forEach(b => { b.style.height = '2px'; b.style.background = 'rgba(255,117,53,.18)'; });
}

// Idle shimmer
(function idleSpec() {
  if (!isTx) {
    for (let i = 0; i < N_BARS; i++) {
      const b = document.getElementById(`sb${i}`);
      if (b && !b.style.height.startsWith('4')) {
        const h = 2 + Math.sin(Date.now() * 0.0018 + i * 0.42) * 1.2;
        b.style.height = `${h}px`;
      }
    }
  }
  requestAnimationFrame(idleSpec);
})();

// ──────────────────────────────────────────
//  RECEIVER
// ──────────────────────────────────────────
const rxSpecCV = $('rxSpecCanvas');
const rxSpecCX = rxSpecCV.getContext('2d');

function resizeRxSpec() {
  rxSpecCV.width  = rxSpecCV.parentElement.offsetWidth  || 600;
  rxSpecCV.height = rxSpecCV.parentElement.offsetHeight || 88;
}
resizeRxSpec();
addEventListener('resize', resizeRxSpec);

function toggleRx() { isRx ? stopRx() : startRx(); }

async function startRx() {
  // Code required
  if (!rxCode) { showCodeEntry(); return; }

  const micId = $('micSel').value;
  try {
    rxStream = await navigator.mediaDevices.getUserMedia({
      audio: {
        deviceId:         micId ? { exact: micId } : undefined,
        echoCancellation: false, noiseSuppression: false,
        autoGainControl: false, sampleRate: 48000,
      }
    });
  } catch(e) { setRxMsg(`Mic error: ${e.message}`); return; }

  rxAC  = new (window.AudioContext || window.webkitAudioContext)();
  const src = rxAC.createMediaStreamSource(rxStream);
  rxAna = rxAC.createAnalyser();
  rxAna.fftSize              = 8192;
  rxAna.smoothingTimeConstant = 0.0;
  src.connect(rxAna);
  rxFD = new Uint8Array(rxAna.frequencyBinCount);
  rxFR = rxAC.sampleRate / rxAna.fftSize;

  isRx = true;
  rxUserPaused = false;
  resetRxState();

  $('btnListen').textContent = 'STOP';
  $('btnListen').classList.add('stopping');
  $('btnPauseRx').disabled = false;
  $('rxLed').className = 'led on-rx';
  setRxMsg('Scanning for start signal…');
  setRxPhase('IDLE — AWAITING START', 'Listening for 180 Hz start tone');

  rxTimer = setInterval(rxTick, 2);
  drawRxSpec();
}

function stopRx() {
  isRx = false;
  rxUserPaused = false;
  clearInterval(rxTimer);       rxTimer = null;
  cancelAnimationFrame(rxRAF);  rxRAF   = null;
  if (rxStream) { rxStream.getTracks().forEach(t => t.stop()); rxStream = null; }
  if (rxAC)    { rxAC.close().catch(() => {}); rxAC = null; }
  $('btnListen').textContent = 'START LISTENING';
  $('btnListen').classList.remove('stopping');
  $('btnPauseRx').disabled = true;
  $('btnPauseRx').textContent = '⏸ PAUSE';
  $('btnPauseRx').classList.remove('active');
  $('rxLed').className = 'led';
  setRxMsg('Stopped');
}

function resetRxState() {
  // Note: rxCode is intentionally NOT cleared here — keep code between sessions
  rxPhase          = 'IDLE';
  rxSyncDet        = 0;
  rxSyncGone       = 0;
  rxDetCFG         = null;
  rxDataStart      = 0;
  rxLastPx         = -1;
  rxPixels         = [];
  rxPxCnt          = 0;
  rxUserPaused     = false;
  rxPauseAnchor    = 0;
  rxTxPaused       = false;
  rxLastSig        = 0;
  rxResumeSyncStart = 0;
  rxResumeSyncGone  = 0;
}

function clearRx() {
  resetRxState();
  setRxPhase('IDLE — AWAITING START', 'Cleared');
  setRxMsg('Cleared');
  $('rxPixelCount').textContent = '0 px';
  $('imgOutput').className = 'img-output';
  const rc = $('rxCanvas');
  rc.getContext('2d').clearRect(0, 0, rc.width, rc.height);
  rc.style.display = 'none';
}

function togglePauseRx() {
  if (!isRx) return;
  if (rxUserPaused) resumeRx(); else pauseRx();
}

function pauseRx() {
  if (!isRx || rxUserPaused) return;
  rxUserPaused  = true;
  rxPauseAnchor = performance.now();
  $('btnPauseRx').textContent = '▶ RESUME';
  $('btnPauseRx').classList.add('active');
  $('rxLed').className = 'led on-rx paused';
  setRxMsg('Paused — press Resume to continue');
}

function resumeRx() {
  if (!isRx || !rxUserPaused) return;
  // Shift the data start anchor forward by the duration we were paused
  const pauseDur = performance.now() - rxPauseAnchor;
  if (rxPhase === 'DATA' && rxDataStart > 0) {
    rxDataStart += pauseDur;  // slides the window forward so timing stays correct
  }
  rxUserPaused = false;
  $('btnPauseRx').textContent = '⏸ PAUSE';
  $('btnPauseRx').classList.remove('active');
  $('rxLed').className = 'led on-rx';
  setRxMsg('Receiving…');
}

// ── FFT helpers ──
function refreshFD() { rxAna.getByteFrequencyData(rxFD); }

function peakIn(fLo, fHi) {
  const b0 = Math.max(0, Math.floor(fLo / rxFR));
  const b1 = Math.min(rxFD.length - 1, Math.ceil(fHi / rxFR));
  let maxM = 0, maxB = b0;
  for (let i = b0; i <= b1; i++) { if (rxFD[i] > maxM) { maxM = rxFD[i]; maxB = i; } }
  return { freq: maxB * rxFR, mag: maxM };
}

// ── Simplified state machine ──
// Phases: IDLE → SYNC → DATA → DONE
// 180 Hz detected in DATA = TX pause/resume signal; recalibrate timing when it ends
function rxTick() {
  if (!rxAna || rxUserPaused) return;
  const now = performance.now();
  refreshFD();

  // ── IDLE: wait for 180 Hz start tone ──
  if (rxPhase === 'IDLE') {
    const pk = peakIn(P.SYNC_F - 40, P.SYNC_F + 40);
    if (pk.mag > P.SYNC_TH) {
      if (!rxSyncDet) rxSyncDet = now;
      if (now - rxSyncDet > 80) {
        rxPhase = 'SYNC'; rxSyncGone = 0;
        setRxPhase('START DETECTED', 'Sync carrier locked — awaiting data');
        setRxMsg('Start signal active…');
      }
    } else { rxSyncDet = 0; }
    return;
  }

  // ── SYNC: wait for 180 Hz to end, then begin DATA ──
  if (rxPhase === 'SYNC') {
    const pk = peakIn(P.SYNC_F - 40, P.SYNC_F + 40);
    if (pk.mag < P.SYNC_TH - 12) {
      if (!rxSyncGone) rxSyncGone = now;
      if (now - rxSyncGone > 30) {
        // Sync ended — set up DATA using rxCode
        const cfg = rxCode
          ? { resolution: rxCode.resolution, nColors: rxCode.nColors, timeMs: rxCode.timeMs }
          : { resolution: 32, nColors: 124, timeMs: 50 };  // fallback (shouldn't happen)

        rxDetCFG    = cfg;
        buildPalette(cfg.nColors);
        setupRxCanvas(cfg.resolution);

        rxPhase      = 'DATA';
        rxDataStart  = now + P.PRE_GAP;
        rxLastPx     = -1;
        rxLastSig    = now;
        rxTxPaused   = false;
        rxResumeSyncStart = 0;
        rxResumeSyncGone  = 0;

        setRxPhase(`RECEIVING — ${cfg.resolution}×${cfg.resolution}`,
                   `${cfg.resolution}×${cfg.resolution} · ${cfg.nColors} colors · ${cfg.timeMs}ms/tone`);
        setRxMsg(`Receiving ${(cfg.resolution * cfg.resolution).toLocaleString()} pixels…`);
      }
    } else { rxSyncGone = 0; }
    return;
  }

  // ── DATA: receive pixel tones ──
  if (rxPhase === 'DATA') {
    const cfg    = rxDetCFG;
    const period = cfg.timeMs + P.PX_GAP;

    // ── Check for END tone (above data band) ──
    const endPk = peakIn(P.END_F - 150, P.END_F + 150);
    if (endPk.mag > P.END_TH && endPk.freq > 5200) { finishRxData(); return; }

    // ── Check for RESUME-SYNC (180 Hz in DATA phase = TX paused and now resuming) ──
    const syncPk = peakIn(P.SYNC_F - 40, P.SYNC_F + 40);
    if (syncPk.mag > P.SYNC_TH) {
      if (!rxResumeSyncStart) {
        rxResumeSyncStart = now;
      } else if (now - rxResumeSyncStart > 120) {
        // TX is sending a resume signal
        rxTxPaused = false;
        rxResumeSyncGone = 0;
        setRxMsg('TX resuming…');
      }
      return;  // Don't process data tones while sync is present
    } else if (rxResumeSyncStart > 0) {
      // Sync just ended — recalibrate timing anchor
      if (!rxResumeSyncGone) rxResumeSyncGone = now;
      if (now - rxResumeSyncGone > 20) {
        // Recalibrate: pixel rxPxCnt will arrive after PRE_GAP
        rxDataStart = rxResumeSyncGone + P.PRE_GAP - rxPxCnt * period;
        rxResumeSyncStart = 0;
        rxResumeSyncGone  = 0;
        rxLastPx = rxPxCnt - 1;  // reset so next index is rxPxCnt
        setRxMsg('Receiving…');
        return;
      }
      return;
    }

    // ── Auto-pause detection (TX gone silent) ──
    const anyPk = peakIn(P.FREQ_LO - 100, P.END_F + 200);
    if (anyPk.mag > P.DATA_TH) rxLastSig = now;
    if (now - rxLastSig > 600 && rxPxCnt > 0) {
      if (!rxTxPaused) {
        rxTxPaused = true;
        setRxMsg('TX paused — waiting for resume…');
        setRxPhase('TX PAUSED', 'Waiting for transmitter to resume');
      }
      return;
    }
    if (rxTxPaused) {
      rxTxPaused = false;
      setRxMsg('Receiving…');
      setRxPhase(`RECEIVING — ${cfg.resolution}×${cfg.resolution}`,
                 `${cfg.resolution}×${cfg.resolution} · ${cfg.nColors} colors · ${cfg.timeMs}ms/tone`);
    }

    // ── Normal pixel sampling ──
    const elapsed = now - rxDataStart;
    if (elapsed < 0) return;

    const total  = cfg.resolution * cfg.resolution;
    const pxIdx  = Math.floor(elapsed / period);
    const pxOff  = elapsed % period;
    const lo     = cfg.timeMs * 0.25;
    const hi     = cfg.timeMs * 0.76;

    if (pxOff >= lo && pxOff <= hi && pxIdx !== rxLastPx && pxIdx < total) {
      rxLastPx = pxIdx;
      const pk = peakIn(P.FREQ_LO - 50, P.FREQ_HI + 50);
      if (pk.mag > P.DATA_TH) {
        const ci = freq2idx(pk.freq, cfg.nColors);
        rxPixels[pxIdx] = ci;
        drawRxPixel(pxIdx, ci, cfg.resolution);
        rxPxCnt++;
        $('rxPixelCount').textContent = `${rxPxCnt} / ${total.toLocaleString()} px`;
      }
    }
    if (pxIdx >= total) finishRxData();
  }
}

function finishRxData() {
  rxPhase = 'DONE';
  const total = rxDetCFG ? rxDetCFG.resolution ** 2 : 0;
  setRxPhase('COMPLETE ✓', `${rxPxCnt.toLocaleString()} of ${total.toLocaleString()} pixels received`);
  setRxMsg(`Done — ${rxPxCnt.toLocaleString()} px received`);
  $('imgOutput').classList.add('has-img');
  $('btnPauseRx').disabled = true;
}

function setupRxCanvas(res) {
  const rc = $('rxCanvas');
  rc.width = rc.height = res;
  const rcx = rc.getContext('2d');
  rcx.fillStyle = '#060B18';
  rcx.fillRect(0, 0, res, res);
  rc.style.display = 'block';
}

function drawRxPixel(idx, ci, res) {
  const rc = $('rxCanvas');
  const [r, g, b] = palette[ci] || [0, 0, 0];
  const ctx = rc.getContext('2d');
  ctx.fillStyle = `rgb(${r},${g},${b})`;
  ctx.fillRect(idx % res, Math.floor(idx / res), 1, 1);
}

function saveImg() {
  const rc = $('rxCanvas');
  Object.assign(document.createElement('a'), {
    download: `audiopix_${Date.now()}.png`,
    href: rc.toDataURL('image/png'),
  }).click();
}

function setRxMsg(m)          { $('rxStatus').textContent    = m; }
function setRxPhase(lbl, sub) { $('rxPhaseLabel').textContent = lbl; $('rxPhaseSub').textContent = sub || ''; }

// RX spectrum drawing
function drawRxSpec() {
  if (!isRx || !rxAna) return;
  rxAna.getByteFrequencyData(rxFD);
  const W = rxSpecCV.width, H = rxSpecCV.height;
  rxSpecCX.fillStyle = 'rgba(0,0,0,0.4)';
  rxSpecCX.fillRect(0, 0, W, H);

  const maxF  = 6600;
  const maxB  = Math.floor(maxF / rxFR);
  const nBars = Math.min(maxB, Math.floor(W / 1.5));
  const bw    = W / nBars;
  const nc    = rxCode ? rxCode.nColors : CFG.nColors;

  for (let i = 0; i < nBars; i++) {
    const bin  = Math.floor(i * maxB / nBars);
    const mag  = rxFD[Math.min(bin, rxFD.length - 1)];
    const bh   = (mag / 255) * H;
    const freq = bin * rxFR;

    let col;
    if (Math.abs(freq - P.SYNC_F) < 42) {
      col = `rgba(80,200,255,${0.5 + mag/512})`;
    } else if (freq > 5200 && freq < 5800) {
      col = `rgba(200,80,255,${0.45 + mag/512})`;
    } else if (freq >= P.FREQ_LO && freq <= P.FREQ_HI) {
      const ci = freq2idx(freq, nc);
      const [r, g, b] = palette[ci] || [0, 200, 200];
      col = `rgba(${r},${g},${b},${0.55 + mag/640})`;
    } else {
      col = `rgba(0,212,200,${0.10 + mag/1400})`;
    }
    rxSpecCX.fillStyle = col;
    rxSpecCX.fillRect(~~(i * bw), H - bh, Math.max(1, bw - 0.5), bh);
  }
  rxRAF = requestAnimationFrame(drawRxSpec);
}

// ──────────────────────────────────────────
//  CONTROLS POPUP
// ──────────────────────────────────────────
function openControls() {
  PND.resolution = CFG.resolution;
  PND.nColors    = CFG.nColors;
  PND.timeMs     = CFG.timeMs;
  $('colSlider').value = CFG.nColors;
  $('resSlider').value = resToSlider(CFG.resolution);
  $('tmSlider').value  = CFG.timeMs;
  updatePopup();
  $('overlay').classList.remove('hidden');
}

function closeControls() { $('overlay').classList.add('hidden'); }
function overlayClick(e) { if (e.target === $('overlay')) closeControls(); }

function applySettings() {
  CFG.resolution = PND.resolution;
  CFG.nColors    = PND.nColors;
  CFG.timeMs     = PND.timeMs;
  buildPalette(CFG.nColors);
  if (origImg) processImage(origImg, CFG.resolution, CFG.nColors);
  refreshPalStrip(CFG.nColors);
  updateBadge();
  updateTxCode();
  closeControls();
}

function sliderToRes(v) { return Math.max(1, Math.min(6000, Math.round(Math.pow(6000, v / 100)))); }
function resToSlider(r) { return Math.round(Math.log(Math.max(1, r)) / Math.log(6000) * 100); }

function onColChange(v) { PND.nColors    = parseInt(v);             updatePopup(); }
function onResChange(v) { PND.resolution = sliderToRes(parseFloat(v)); updatePopup(); }
function onTmChange(v)  { PND.timeMs     = parseInt(v);             updatePopup(); }

function updatePopup() {
  const { resolution: res, nColors: nc, timeMs: tm } = PND;

  $('colVal').textContent = `${nc}`;
  $('resVal').textContent = `${res}×${res}`;
  $('tmVal').textContent  = `${tm}ms`;

  buildPalette(nc);
  const pp = $('palPreview');
  pp.innerHTML = '';
  palette.forEach(([r,g,b]) => {
    const s = document.createElement('div');
    s.className = 'pal-swatch';
    s.style.background = `rgb(${r},${g},${b})`;
    pp.appendChild(s);
  });

  const rg = $('resGrid');
  const n  = Math.min(res, 14);
  rg.style.gridTemplateColumns = `repeat(${n},1fr)`;
  rg.innerHTML = '';
  for (let i = 0; i < n * n; i++) {
    const d = document.createElement('div');
    d.className = 'res-grid-cell';
    d.style.background = `hsl(${(i*137.508)%360},60%,${30+(i%5)*10}%)`;
    rg.appendChild(d);
  }
  $('resStats').textContent = `${(res*res).toLocaleString()} pixels`;

  $('speedFill').style.width = `${(tm / 200) * 100}%`;
  $('speedLabel').textContent =
    tm <=  8 ? 'Ultrafast' : tm <= 20 ? 'Fast' :
    tm <= 60 ? 'Normal'    : tm <=120 ? 'Slow' : 'Very slow';

  const { pixels, startMs, dataMs, endMs, total } = calcEst(res, nc, tm);

  $('estPx').textContent    = pixels.toLocaleString();
  $('estHdr').textContent   = fmtTime(startMs);
  $('estTotal').textContent = fmtTime(total);

  $('estNote').textContent =
    total > 18000000 ? '⚠ Multi-hour transfer!'  :
    total >  3600000 ? '⏳ Hours to complete'     :
    total >   600000 ? '☕ Coffee break needed'   :
    total >    60000 ? '⏱ Under ' + Math.ceil(total/60000) + ' min' :
    total >    10000 ? '⚡ Under a minute'        :
                       '🚀 Super fast!';

  if (total > 0) {
    $('etlSync').style.flex = startMs;
    $('etlData').style.flex = dataMs;
    $('etlEnd').style.flex  = endMs;
  }

  // Live code preview in settings popup
  if ($('settingsCodeVal')) {
    $('settingsCodeVal').textContent = encodeCode(res, nc, tm);
  }
}

function refreshPalStrip(n) {
  buildPalette(n);
  const strip = $('palStripTx');
  strip.innerHTML = '';
  palette.forEach(([r,g,b]) => {
    const s = document.createElement('div');
    s.className = 'pal-sw';
    s.style.background = `rgb(${r},${g},${b})`;
    strip.appendChild(s);
  });
  $('palCountTx').textContent = `${n} colors`;
}

function updateBadge() {
  $('settingsBadge').textContent = `${CFG.resolution}px · ${CFG.nColors}c · ${CFG.timeMs}ms`;
}

// ──────────────────────────────────────────
//  INIT
// ──────────────────────────────────────────
buildPalette(CFG.nColors);
buildSpecBars();
refreshPalStrip(CFG.nColors);
updateBadge();
updateTxCode();
updatePopup();
enumDevices();
